# Generated by Django 3.2.4 on 2021-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='baozhi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='biaozhun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='chandi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='chengfen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='xukezheng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
